name = "oauth-app"
main = "src/index.ts"
compatibility_date = "2023-04-06"
kv_namespaces = [
  { binding = "INSTALLATIONS", id = "da0e68109d194f26a80e07ec01b980b5", preview_id = "d8082a74891442aa9d315985f067b870" },
  { binding = "OAUTH_STATES", id = "314f55b2cc5f43bc802b0455829af955", preview_id = "c6c713d5e3184ef3a6f918da4c892ef7" },
]

[vars]
SLACK_SIGNING_SECRET=""
SLACK_CLIENT_ID=""
SLACK_CLIENT_SECRET=""
SLACK_BOT_SCOPES="commands,chat:write,app_mentions:read"
SLACK_OIDC_SCOPES="openid,email,profile"
SLACK_OIDC_REDIRECT_URI=""