name = "oauth-app"
main = "src/index.ts"
compatibility_date = "2023-04-06"
kv_namespaces = [
  { binding = "SLACK_INSTALLATIONS", id = "976f5703de1b44cdab3826d9025f43ad", preview_id = "68b91d924b9e45189e7562ac12950e63" },
  { binding = "SLACK_OAUTH_STATES", id = "428a7013ffb14465b4935a13fffb3afb", preview_id = "1dd1494816ef4d998d7d47e6c27d53a2" },
]

[vars]
SLACK_BOT_SCOPES="commands,chat:write,app_mentions:read"
SLACK_OIDC_SCOPES="openid,email,profile"
